### ISSUE TITLE
What is this.

### ISSUE THREAD

**Issue by ghost** [Devaprise/Targo-Tap#1]
Just wondering, what is this thing? It's some "_app_"...

**Comment by razetime** [comment]
@mathdude314 (The #1 Base-12 Proponent)
It's actually a program.
for now, the goal of the game is to keep clicking the numbers that are display inside the square in the middle.
There's supposed to be more gamemodes that we'll add soon.
Got it?

**Comment by IdrissDimson** [comment]
@mathdude314 yeah it's gonna be the Targo Tap app when we're done with it.
